In [5]:

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
import tensorflow as tf
from tensorflow import keras

C:\Users\ariha\AppData\Local\Temp\ipykernel_27900\1821982272.py:2: DeprecationWarning: 
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466
        
  import pandas as pd


In [6]:
train = pd.read_csv(r'C:\Users\ariha\OneDrive - IIT Kanpur\Desktop\train.csv')
train.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [7]:
train.Embarked.unique()

array(['S', 'C', 'Q', nan], dtype=object)

In [8]:
sex_binary_test = pd.read_csv(r'C:\Users\ariha\OneDrive - IIT Kanpur\Desktop\gender_submission.csv')
sex_binary_test.head()

PassengerId  Survived
0          892         0
1          893         1
2          894         0
3          895         0
4          896         1

In [9]:
test = pd.read_csv(r'C:\Users\ariha\OneDrive - IIT Kanpur\Desktop\test.csv')
test.head()

PassengerId  Pclass                                          Name     Sex  \
0          892       3                              Kelly, Mr. James    male   
1          893       3              Wilkes, Mrs. James (Ellen Needs)  female   
2          894       2                     Myles, Mr. Thomas Francis    male   
3          895       3                              Wirz, Mr. Albert    male   
4          896       3  Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female   

    Age  SibSp  Parch   Ticket     Fare Cabin Embarked  
0  34.5      0      0   330911   7.8292   NaN        Q  
1  47.0      1      0   363272   7.0000   NaN        S  
2  62.0      0      0   240276   9.6875   NaN        Q  
3  27.0      0      0   315154   8.6625   NaN        S  
4  22.0      1      1  3101298  12.2875   NaN        S

In [10]:
x_train = train[['Pclass','Sex','Age','Fare','Embarked','SibSp','Parch']]
x_train['Sex'] = x_train['Sex'].replace({'male':1,'female':0})
x_train['Embarked'].replace('Q', 0,inplace=True)
x_train['Embarked'].replace('S', 1,inplace=True)
x_train['Embarked'].replace('C', 2,inplace=True)
x_train['Age'] = x_train['Age']/100
x_train['Fare'] = x_train['Fare']/512.3292
x_train.head()

C:\Users\ariha\AppData\Local\Temp\ipykernel_27900\1712376321.py:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  x_train['Sex'] = x_train['Sex'].replace({'male':1,'female':0})
C:\Users\ariha\AppData\Local\Temp\ipykernel_27900\1712376321.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  x_train['Sex'] = x_train['Sex'].replace({'male':1,'female':0})
C:\Users\ariha\AppData\Local\Temp\ipykernel_27900\1712376321.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment 

Pclass  Sex   Age      Fare  Embarked  SibSp  Parch
0       3    1  0.22  0.014151       1.0      1      0
1       1    0  0.38  0.139136       2.0      1      0
2       3    0  0.26  0.015469       1.0      0      0
3       1    0  0.35  0.103644       1.0      1      0
4       3    1  0.35  0.015713       1.0      0      0

In [11]:
y_train = train['Survived']
y_train = y_train.to_numpy()
y_train

array([0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1,
       1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0,
       1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1,

In [12]:
x_test = test[['Pclass','Sex','Age','Fare','Embarked','SibSp','Parch']]
x_test = x_test.replace({'male':1,'female':0})
x_test['Embarked'].replace('Q', 0,inplace=True)
x_test['Embarked'].replace('S', 1,inplace=True)
x_test['Embarked'].replace('C', 2,inplace=True)
x_test['Age'] = x_test['Age']/100
x_test['Fare'] = x_test['Fare']/512.3292
x_test.head()

C:\Users\ariha\AppData\Local\Temp\ipykernel_27900\2695997193.py:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  x_test = x_test.replace({'male':1,'female':0})
C:\Users\ariha\AppData\Local\Temp\ipykernel_27900\2695997193.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  x_test['Embarked'].replace(

Pclass  Sex    Age      Fare  Embarked  SibSp  Parch
0       3    1  0.345  0.015282         0      0      0
1       3    0  0.470  0.013663         1      1      0
2       2    1  0.620  0.018909         0      0      0
3       3    1  0.270  0.016908         1      0      0
4       3    0  0.220  0.023984         1      1      1

In [13]:
x_train = x_train.fillna(x_train.mean())
len(x_train)

891

In [14]:
x_test = x_test.fillna(x_test.mean())
len(x_test)

418

In [15]:
x_train.Fare.max(),x_test.Fare.max()

(1.0, 1.0)

In [16]:
x_train_arr = x_train.to_numpy()
x_test_arr = x_test.to_numpy()

In [27]:
x_train_arr

array([[3.        , 1.        , 0.22      , ..., 1.        , 1.        ,
        0.        ],
       [1.        , 0.        , 0.38      , ..., 2.        , 1.        ,
        0.        ],
       [3.        , 0.        , 0.26      , ..., 1.        , 0.        ,
        0.        ],
       ...,
       [3.        , 0.        , 0.29699118, ..., 1.        , 1.        ,
        2.        ],
       [1.        , 1.        , 0.26      , ..., 2.        , 0.        ,
        0.        ],
       [3.        , 1.        , 0.32      , ..., 0.        , 0.        ,
        0.        ]])

In [18]:
x_test_arr

array([[3.       , 1.       , 0.345    , ..., 0.       , 0.       ,
        0.       ],
       [3.       , 0.       , 0.47     , ..., 1.       , 1.       ,
        0.       ],
       [2.       , 1.       , 0.62     , ..., 0.       , 0.       ,
        0.       ],
       ...,
       [3.       , 1.       , 0.385    , ..., 1.       , 0.       ,
        0.       ],
       [3.       , 1.       , 0.3027259, ..., 1.       , 0.       ,
        0.       ],
       [3.       , 1.       , 0.3027259, ..., 2.       , 1.       ,
        1.       ]])

In [19]:
model = keras.Sequential([
    keras.layers.Dense(100, input_shape=(7,), activation='relu'),
    keras.layers.Dense(50, activation='relu'),
    keras.layers.Dense(50, activation='relu'),
    keras.layers.Dense(25, activation='relu'),
    keras.layers.Dense(1, activation='sigmoid')
])

model.compile(optimizer='adam',
              loss='binary_crossentropy',
              metrics=['accuracy'])

model.fit(x_train_arr, y_train, epochs=200)

c:\CODE\PYTHON_CODE\.venv\Lib\site-packages\keras\src\layers\core\dense.py:88: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Epoch 1/200
28/28 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.6158 - loss: 0.6375
Epoch 2/200
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7148 - loss: 0.5602 
Epoch 3/200
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7603 - loss: 0.5437 
Epoch 4/200
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7861 - loss: 0.4906 
Epoch 5/200
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7768 - loss: 0.4819 
Epoch 6/200
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8314 - loss: 0.4092 
Epoch 7/200
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8058 - loss: 0.4357 
Epoch 8/200
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8057 - loss: 0.4423 
Epoch 9/200
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7958 - loss: 0.4678 
Epoch 10/200
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 942us/step - accuracy: 0.7987 - loss: 0.4483
Epoch 11/200
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8030 - loss: 0.4521 
Epoch 12/200
28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 664us/ste

In [20]:
model.evaluate(x_train_arr,y_train)

28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 989us/step - accuracy: 0.8625 - loss: 0.3204


[0.29854249954223633, 0.875420868396759]

In [21]:
predict = model.predict(x_train_arr)
predict = predict>0.5
predict = 1*predict
predict = predict.reshape(-1,)
predict

28/28 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step


array([0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0,
       1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1,
       1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0,
       1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1,

In [22]:
y_train

array([0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1,
       1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0,
       1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1,

In [23]:
predict = model.predict(x_test_arr)
predict = predict>0.5
predict = 1*predict
predict = predict.reshape(-1,)
Id = test.PassengerId
Id = pd.DataFrame(Id)
predict = pd.DataFrame(predict)
predict.columns = ['Survived']
Id,predict

14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step 


(     PassengerId
 0            892
 1            893
 2            894
 3            895
 4            896
 ..           ...
 413         1305
 414         1306
 415         1307
 416         1308
 417         1309
 
 [418 rows x 1 columns],
      Survived
 0           0
 1           0
 2           0
 3           0
 4           1
 ..        ...
 413         0
 414         1
 415         0
 416         0
 417         1
 
 [418 rows x 1 columns])

In [24]:
output = Id
output.insert(1,'Survived',predict)
output

PassengerId  Survived
0            892         0
1            893         0
2            894         0
3            895         0
4            896         1
..           ...       ...
413         1305         0
414         1306         1
415         1307         0
416         1308         0
417         1309         1

[418 rows x 2 columns]

In [25]:
output.to_csv('titanic_kaggle_submit.csv', sep=',', index=False, encoding='utf-8')